In [1]:
import gymnasium as gym
from irbfn_mpc.nonlinear_mpc import NMPCPlanner
from irbfn_mpc.planner_utils import intersect_point, nearest_point_on_trajectory
import numpy as np

2024-06-07 15:12:36.976308: W external/xla/xla/service/gpu/nvptx_compiler.cc:760] The NVIDIA driver's CUDA version is 12.4 which is older than the ptxas CUDA version (12.5.40). Because the driver is older than the ptxas version, XLA is disabling parallel compilation, which may slow down compilation. You should update your NVIDIA driver or use the NVIDIA-provided CUDA forward compatibility packages.


In [2]:
from IPython.display import HTML, display
%matplotlib inline

In [3]:
env = gym.make(
    "f1tenth_gym:f1tenth-v0",
    config={
        "observation_config": {"type": "kinematic_state"},
        "num_agents": 1,
    },
    render_mode="rgb_array",
)
env = gym.wrappers.RecordVideo(env, "video_nmpc")

/usr/local/lib/python3.12/dist-packages/gymnasium/wrappers/record_video.py:94: UserWarning: WARN: Overwriting existing videos at /home/irbfn/scripts/video_nmpc folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(


In [4]:
track = env.unwrapped.track
waypoints = np.stack([track.centerline.xs, track.centerline.ys, track.centerline.vxs, track.centerline.yaws]).T

In [5]:
mpc = NMPCPlanner()

In [6]:
def get_current_waypoint(waypoints, lookahead_distance, position, theta):
    wpts = waypoints[:, :2]
    lookahead_distance = np.float32(lookahead_distance)
    nearest_point, nearest_dist, t, i = nearest_point_on_trajectory(position, wpts)
    if nearest_dist < lookahead_distance:
        t1 = np.float32(i + t)
        lookahead_point, i2, t2 = intersect_point(
            position, lookahead_distance, wpts, t1, wrap=True
        )
        if i2 is None:
            return None, None
        current_waypoint = np.empty((3,), dtype=np.float32)
        # x, y
        current_waypoint[0:2] = wpts[i2, :]
        # speed
        current_waypoint[2] = waypoints[i, -1]
        return current_waypoint, i
    elif nearest_dist < 20:
        return wpts[i, :], i
    else:
        return None, None

In [12]:
obs, info = env.reset()
done = False

ld = 1.5
step = 0

while not done and step < 300:
    current_state = obs["agent_0"]
    goal, goal_i = get_current_waypoint(
        waypoints, ld, np.array([current_state["pose_x"], current_state["pose_y"]]), current_state["pose_theta"]
    )
    goal_state = np.array([goal[0], goal[1], 0.0, goal[2], waypoints[goal_i, 3]])
    speeds, steers = mpc.plan(current_state, goal_state)
    action = env.action_space.sample()
    action[0] = [steers[0], speeds[0]]
    print(goal_state)

    obs, step_reward, done, truncated, info = env.step(action)
    step += 1

env.close()

[-1.44858015 -0.38937837  0.         -2.87898374 -2.87898374]
[-1.44858015 -0.38937837  0.         -2.87898374 -2.87898374]
[-1.44858015 -0.38937837  0.         -2.87898374 -2.87898374]
[-1.44858015 -0.38937837  0.         -2.87898374 -2.87898374]
[-1.44858015 -0.38937837  0.         -2.87898374 -2.87898374]
[-1.44858015 -0.38937837  0.         -2.87898374 -2.87898374]
[-1.44858015 -0.38937837  0.         -2.87898374 -2.87898374]
[-1.44858015 -0.38937837  0.         -2.87898374 -2.87898374]
[-1.44858015 -0.38937837  0.         -2.87898374 -2.87898374]
[-1.44858015 -0.38937837  0.         -2.87898374 -2.87898374]
[-1.44858015 -0.38937837  0.         -2.87898374 -2.87898374]
[-1.44858015 -0.38937837  0.         -2.87898374 -2.87898374]
[-1.44858015 -0.38937837  0.         -2.87898374 -2.87898374]
[-1.44858015 -0.38937837  0.         -2.87898374 -2.87898374]
[-1.44858015 -0.38937837  0.         -2.87898374 -2.87898374]
[-1.44858015 -0.38937837  0.         -2.87898374 -2.87898374]
[-1.4485

Moviepy - Done !
Moviepy - video ready /home/irbfn/scripts/video_nmpc/rl-video-episode-0.mp4


In [13]:
import glob
import io
import base64

for video_file in glob.glob("video_nmpc/*.mp4"):
    video = io.open(video_file, "rb").read()
    encoded = base64.b64encode(video).decode("ascii")
    display(
        HTML(
            f"""<video width="360" height="auto" controls>
                <source src="data:video/mp4;base64,{encoded}" type="video/mp4" />
            </video>"""
        )
    )